In [9]:
import pandas as pd

In [19]:
data ={"name":["a","b","c","d","a","c"],"eng":[8,7,5,8,8,5],"hindi":[2,3,4,5,2,4]}

In [21]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      4

In [24]:
df["duplicated"] = df.duplicated()

In [40]:
df

  name  eng  hindi  duplicated
0    a    8      2       False
1    b    7      3       False
2    c    5      4       False
3    d    8      5       False
4    a    8      2        True
5    c    5      4        True

In [44]:
df.drop_duplicates(inplace = True)

In [45]:
df

  name  eng  hindi  duplicated
0    a    8      2       False
1    b    7      3       False
2    c    5      4       False
3    d    8      5       False
4    a    8      2        True
5    c    5      4        True