In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame({"size":["s","l","x"]})

In [8]:
df.head(4)

  size
0    s
1    l
2    x

In [20]:
ord_data = [["s","m","l","x"]]

In [21]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
oe = OrdinalEncoder()
oe.fit(df[["size"]])

OrdinalEncoder()

In [30]:
df["size_en"]= oe.transform(df[["size"]])

In [31]:
df

  size  size_en
0    s      1.0
1    l      0.0
2    x      2.0

In [ ]:
# map ke thuru

In [39]:
ord_data1 ={"s":0,"m":1,"l":2,"x":3}

In [40]:
df["size_en_map"]= df["size"].map(ord_data1)

In [41]:
df

  size  size_en  size_en_map
0    s      1.0            0
1    l      0.0            2
2    x      2.0            3

In [42]:
dataset =pd.read_csv("e.csv")

In [43]:
dataset.head(4)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y

In [44]:
dataset["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [46]:
dataset["Property_Area"].fillna(dataset["Property_Area"].mode(0),inplace= True)

In [47]:
en_data_ord =[['Urban', 'Rural', 'Semiurban']]

In [50]:
from sklearn.preprocessing import OrdinalEncoder

In [51]:
one =OrdinalEncoder()

In [53]:
dataset["Property_Area"]=one.fit_transform(dataset[["Property_Area"]])

In [55]:
dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2.0,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0.0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2.0,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2.0,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,0.0,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,0.0,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,2.0,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,2.0,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,1.0,N